### ISSUE TITLE
Дока не открывается

### ISSUE THREAD

**Issue by M1h4n1k** [to4no4sv/VKMusix#2]
https://vkmusix.ru/docs не открывается и с впном и без

С впном:
![{9AC56974-68F3-44DD-B7B3-40D14BD3C8F8}](https://github.com/user-attachments/assets/37d2acb1-e566-4a76-852a-8da3fe5ea249)

Без:
![{A50C73BB-29CE-4515-B2DD-82FD6AD74F8A}](https://github.com/user-attachments/assets/9eb1e542-9a8c-4ba4-9920-fc8b1f919c83)

**Comment by to4no4sv** [comment]
пока ещё не сделана

**Comment by to4no4sv** [comment]
ура документация есть
но пока без методов и ошибок
добавлю со временем

https://to4no4sv.gitbook.io/vkmusix
https://to4no4sv.gitbook.io/vkmusix
https://to4no4sv.gitbook.io/vkmusix
